In [1]:
# importing required libraries
import pandas as pd
import numpy as np

In [2]:
# reading data as Dataframe
df = pd.read_csv("BostonHousing.csv")
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [3]:
# Get NA value 
df.isna()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,False,False,False,False,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False
505,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
# Get NA value count per Column 
df.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         5
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [5]:
# Absolute value fill NA Value
df.fillna(0)
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [6]:
# Forward fill NA Value
df.fillna(method='ffill')
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22324\2920060727.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [7]:
# Backward fill NA Value
df.fillna(method='bfill')
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22324\181875011.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [8]:
# mean fill NA Value
df['rm'].fillna(df['rm'].mean())
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [9]:
# median fill NA Value
df['rm'].fillna(df['rm'].median())
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [10]:
# Drop NA Value
df.dropna(inplace = True)

In [11]:
# input
inp = df.drop(columns=["medv"])
inp[75:80]

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
78,0.05646,0.0,12.83,0,0.437,6.232,53.7,5.0141,5,398,18.7,386.40,12.34
79,0.08387,0.0,12.83,0,0.437,5.874,36.6,4.5026,5,398,18.7,396.06,9.10
80,0.04113,25.0,4.86,0,0.426,6.727,33.5,5.4007,4,281,19.0,396.90,5.29
81,0.04462,25.0,4.86,0,0.426,6.619,70.4,5.4007,4,281,19.0,395.63,7.22
82,0.03659,25.0,4.86,0,0.426,6.302,32.2,5.4007,4,281,19.0,396.90,6.72

In [12]:
# output
out = df["medv"]
out

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 501, dtype: float64

In [13]:
# to split data into train and test sets
from sklearn.model_selection import train_test_split as tts

In [14]:
trainx, testx, trainy, testy = tts(inp, out, test_size=0.2, random_state=36)

In [15]:
trainx

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
71,0.15876,0.0,10.81,0,0.4130,5.961,17.5,5.2873,4,305,19.2,376.94,9.88
81,0.04462,25.0,4.86,0,0.4260,6.619,70.4,5.4007,4,281,19.0,395.63,7.22
345,0.03113,0.0,4.39,0,0.4420,6.014,48.5,8.0136,3,352,18.8,385.64,10.53
365,4.55587,0.0,18.10,0,0.7180,3.561,87.9,1.6132,24,666,20.2,354.70,7.12
331,0.05023,35.0,6.06,0,0.4379,5.706,28.4,6.6407,1,304,16.9,394.02,12.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,2.01019,0.0,19.58,0,0.6050,7.929,96.2,2.0459,5,403,14.7,369.30,3.70
429,9.33889,0.0,18.10,0,0.6790,6.380,95.6,1.9682,24,666,20.2,60.72,24.08
419,11.81230,0.0,18.10,0,0.7180,6.824,76.5,1.7940,24,666,20.2,48.45,22.74
102,0.22876,0.0,8.56,0,0.5200,6.405,85.4,2.7147,5,384,20.9,70.80,10.63
138,0.24980,0.0,21.89,0,0.6240,5.857,98.2,1.6686,4,437,21.2,392.04,21.32

In [16]:
trainy

71     21.7
81     23.9
345    17.5
365    27.5
331    17.1
       ...
166    50.0
429     9.5
419     8.4
102    18.6
138    13.3
Name: medv, Length: 400, dtype: float64

In [17]:
testx

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
14,0.63796,0.0,8.14,0,0.538,6.096,84.5,4.4619,4,307,21.0,380.02,10.26
309,0.34940,0.0,9.90,0,0.544,5.972,76.7,3.1025,4,304,18.4,396.24,9.97
185,0.06047,0.0,2.46,0,0.488,6.153,68.8,3.2797,3,193,17.8,387.11,13.15
473,4.64689,0.0,18.10,0,0.614,6.980,67.6,2.5329,24,666,20.2,374.68,11.66
265,0.76162,20.0,3.97,0,0.647,5.560,62.8,1.9865,5,264,13.0,392.40,10.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,1.46336,0.0,19.58,0,0.605,7.489,90.8,1.9709,5,403,14.7,374.43,1.73
162,1.83377,0.0,19.58,1,0.605,7.802,98.2,2.0407,5,403,14.7,389.61,1.92
452,5.09017,0.0,18.10,0,0.713,6.297,91.8,2.3682,24,666,20.2,385.09,17.27
167,1.80028,0.0,19.58,0,0.605,5.877,79.2,2.4259,5,403,14.7,227.61,12.14
363,4.22239,0.0,18.10,1,0.770,5.803,89.0,1.9047,24,666,20.2,353.04,14.64

In [18]:
testy

14     18.2
309    20.3
185    29.6
473    29.8
265    22.8
       ...
161    50.0
162    50.0
452    16.1
167    23.8
363    16.8
Name: medv, Length: 101, dtype: float64

In [19]:
# Importing classifier LinearRegression
from sklearn.linear_model import LinearRegression as LR

In [20]:
# model building
model = LR()
model.fit(trainx, trainy)

LinearRegression()

In [21]:
# m1, m2, ... values
model.coef_

array([-1.18893243e-01,  4.62008366e-02,  7.09909497e-03,  2.43441265e+00,
       -1.43194721e+01,  3.88728389e+00, -7.88153406e-03, -1.55343599e+00,
        2.97995476e-01, -1.22443102e-02, -9.16062951e-01,  1.02027158e-02,
       -5.69466107e-01])

In [22]:
# c value
model.intercept_

np.float64(34.63310469823203)

In [23]:
model.score(testx,testy)

0.6344520336870826

In [24]:
# Test new data
new = np.array( [0.05646,	0.0,	12.83,	0,	0.437,	6.232,	53.7,	5.0141,	5,	398,	18.7,	386.40,	12.34])
new

array([5.6460e-02, 0.0000e+00, 1.2830e+01, 0.0000e+00, 4.3700e-01,
       6.2320e+00, 5.3700e+01, 5.0141e+00, 5.0000e+00, 3.9800e+02,
       1.8700e+01, 3.8640e+02, 1.2340e+01])

In [25]:
# Predict value
model.predict([new])

C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([20.87457786])

In [26]:
# Predict xtest
predy = model.predict(testx)
predy

array([ 1.92409536e+01,  2.36421625e+01,  2.46228889e+01,  2.57581984e+01,
        2.86637784e+01,  1.98034652e+01,  2.01897245e+01,  2.49510457e+01,
        2.46300874e+01,  1.42430248e+01,  2.51506178e+01,  2.07832751e+01,
        3.46710902e+01,  2.66353264e+01,  3.13573142e+01,  3.52258831e+01,
        3.19208675e+01,  3.02791938e+01,  2.97572627e+01,  1.82034400e+01,
        2.54801109e+01,  2.92819137e+01,  2.90497944e+01,  2.26149547e+01,
        2.27362185e+01,  1.72828784e+01,  1.18849000e+01,  1.30252602e+01,
        2.25417701e+01,  2.83892802e+01,  3.35467744e+01,  1.95659205e+01,
        2.49888562e+01,  3.07823920e+01,  1.00493513e+01,  2.75465235e+01,
        1.71722501e+01, -2.14197497e-02,  1.64015963e+01,  2.89215942e+01,
        2.84784358e+01,  2.41456976e+01,  2.87279267e+01,  2.23408939e+01,
        3.41032256e+01,  5.29166544e+00,  1.23805801e+01,  1.14453468e+01,
        1.24280706e+01,  2.77777788e+01,  3.75107078e+01,  2.31228098e+01,
        2.04452433e+01,  1.22993877e+01,  3.10267090e+01,  1.57166218e+01,
        1.80317690e+01,  1.59386541e+01,  3.16556083e+01,  1.56353548e+01,
        1.40909459e+01,  1.38390551e+01,  2.13473713e+01,  2.01222562e+01,
        4.74855665e+00,  2.26714583e+01,  2.57714358e+01,  2.73580923e+01,
        2.21431405e+01,  1.71598775e+01,  2.46353927e+01,  1.62134934e+01,
        2.58450396e+01,  8.62631249e+00,  7.50226127e+00,  1.93835646e+01,
        2.82582362e+01,  2.28912320e+01,  2.24629557e+01,  2.72379744e+01,
        1.93631532e+01,  1.32165445e+01,  3.37339925e+01,  3.29021738e+01,
        2.70608434e+01,  2.01520054e+01,  2.06021092e+01,  2.08268029e+01,
        2.53217028e+01, -6.06367679e+00,  1.58492938e+01,  1.37440060e+01,
        1.21806239e+01,  1.68947675e+01,  2.44039893e+01,  3.11499046e+01,
        3.71938210e+01,  4.06808398e+01,  1.86094760e+01,  2.28459694e+01,
        2.03233184e+01])

In [27]:
# Create testy(actual) predy(predicted by model) residue( abs(testy-predy) )
r = pd.DataFrame({"Actual" : testy, "Predicted" : predy, "Residue" : abs(testy-predy)})
r

     Actual  Predicted    Residue
14     18.2  19.240954   1.040954
309    20.3  23.642163   3.342163
185    29.6  24.622889   4.977111
473    29.8  25.758198   4.041802
265    22.8  28.663778   5.863778
..      ...        ...        ...
161    50.0  37.193821  12.806179
162    50.0  40.680840   9.319160
452    16.1  18.609476   2.509476
167    23.8  22.845969   0.954031
363    16.8  20.323318   3.523318

[101 rows x 3 columns]

In [28]:
# Mean Absolute Error Manually
m = ( sum(r['Residue']) )/( len(r['Residue']) )
m

3.4907060393614353

In [29]:
# Mean Absolute Error using Library
from sklearn.metrics import mean_absolute_error as mae
m = mae(r['Actual'],r['Predicted'])
m

3.4907060393614353